### ISSUE TITLE
Remove "+New" button to create directories?

### ISSUE THREAD

**Issue by Thatoo** [nextcloud-libraries/nextcloud-dialogs#1396]
I just wonder how to remove this "+New" button that allow to add a new folder and we don't need/want in the picker app...

I'm not sure which method I should call https://nextcloud-libraries.github.io/nextcloud-dialogs/classes/index.FilePickerBuilder.html#allowDirectories

![image](https://github.com/user-attachments/assets/1bb3eef6-aeb8-44c0-9267-98217f351d24)

**Comment by skjnldsv** [comment]
```css
.file-picker__main .breadcrumb__actions {
	display: none !important;
}
```
Not supported, nor planned to be implemented.
This should do the trick, but this is succeptible to change, we do not support nor recommand you customizing your Nextcloud that way. Good luck :v:
